// swift-tools-version: 5.9
// SGR Vision SDK — iOS / macOS (Metal). Distribution package (binaryTarget).
// Generated by vision-sdk-ios/scripts/publish.sh for 0.1.9 — do not edit by hand.
import PackageDescription

let package = Package(
    name: "SGRVision",
    platforms: [
        .iOS(.v15),
        .macOS(.v12)
    ],
    products: [
        .library(name: "SGRVision", targets: ["SGRVision"])
    ],
    targets: [
        .binaryTarget(
            name: "SGRVision",
            url: "https://github.com/SGRsoft-Dev/vision-ios-sdk/releases/download/0.1.9/SGRVision.xcframework.zip",
            checksum: "c4fd6e5a0a4db79ad2baed91283a3bde29b3d122268c7a04b2721a0024cfdf6e"
        )
    ]
)
