// swift-tools-version: 5.9
// SGR Vision SDK — iOS / macOS (Metal). Distribution package (binaryTarget).
// Generated by vision-sdk-ios/scripts/publish.sh for 0.1.8 — do not edit by hand.
import PackageDescription

let package = Package(
    name: "SGRVision",
    platforms: [
        .iOS(.v15),
        .macOS(.v12)
    ],
    products: [
        .library(name: "SGRVision", targets: ["SGRVision"])
    ],
    targets: [
        .binaryTarget(
            name: "SGRVision",
            url: "https://github.com/SGRsoft-Dev/vision-ios-sdk/releases/download/0.1.8/SGRVision.xcframework.zip",
            checksum: "47430360da0b53c82753bb45d38a667ed9329a6d02f51551dc4bcd16c5891cbc"
        )
    ]
)
