// swift-tools-version: 5.9
// SGR Vision SDK — iOS / macOS (Metal). Distribution package (binaryTarget).
// Generated by vision-sdk-ios/scripts/publish.sh for 0.1.7 — do not edit by hand.
import PackageDescription

let package = Package(
    name: "SGRVision",
    platforms: [
        .iOS(.v15),
        .macOS(.v12)
    ],
    products: [
        .library(name: "SGRVision", targets: ["SGRVision"])
    ],
    targets: [
        .binaryTarget(
            name: "SGRVision",
            url: "https://github.com/SGRsoft-Dev/vision-ios-sdk/releases/download/0.1.7/SGRVision.xcframework.zip",
            checksum: "8f4861bebe7c19daf92e62a723dd18d8d4d883881027ba880e6466282acfe5a4"
        )
    ]
)
